### ISSUE TITLE
执行了start之后，parcel控制台输出一直卡在Building不动

### ISSUE THREAD

**Issue by dxk19911212** [athm-fe/parcel-demo#5]
依赖安装完毕，执行start，控制台输出显示Building....然后就没动静了，请问有可能是什么问题造成的？

**Comment by jpuncle** [comment]
@dxk19911212 提供下更详细的信息吧，OS、Node 版本、报错信息等等

**Comment by dxk19911212** [comment]
windows
node v9.11.1
yarn v1.6.0

没有报错，就是一直卡在building中，信息如下：
> parcel-demo@1.0.0 start D:\project\parcel-demo
> parcel src/*.html --no-cache

Server running at http://localhost:1234 
∞  Building...
∞  Building index.html...∞  Building list.html...∞  Building list.js...∞  Building car.jpg...∞  Building index.js...∞  Building list.css...∞  Building index.scss...∞  Building play.png...∞  Building modES6.js...∞  Building modCommonJS.js...∞  Building index.scss...∞  Building normalize.css...∞  Building core.js...

就是一直卡在building core.js这里，然后我把package.json中的lodash依赖去掉，就可以了。。估计是打包core.js时出了问题？。。

github上找了一圈就发现你也在跟进parcel，感觉不错 : )
